### ISSUE TITLE
Elasticsearch check not working

### ISSUE THREAD

**Issue by eplanet** [DataDog/workbench-recipes#2]
I get the following error when starting either flavor of elasticsearch:

```bash
instance #0 [ERROR]: "HTTPConnectionPool(host='172.18.0.3', port=9200): 
Max retries exceeded with url: /_nodes/_local/stats?all=true (Caused by 
NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 
0x7f33deaa45d0>: Failed to establish a new connection: [Errno 111] Connection refused',))"
```

**Comment by xvello** [comment]
Hi!

The recipe is using the `workbench` network and the auto_conf looks good. To me, it looks like ES is refusing access based on IP filtering. A `curl` from the host also fails, so that's the best bet.

I tried changing `network.host=0.0.0.0` in the envvars, but got this error:
```
[2017-06-26T08:26:09,747][INFO ][o.e.t.TransportService   ] [IvQLoBg] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2017-06-26T08:26:09,756][INFO ][o.e.b.BootstrapChecks    ] [IvQLoBg] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
```

Trying `network.host=_global_` also yields an error:
```
[2017-06-26T08:34:01,772][INFO ][o.e.n.Node               ] [IvQLoBg] starting ...
[2017-06-26T08:34:02,090][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running global-scope (public) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.2.jar:5.4.2]
```
We'll have to investigate the ES configuration

**Comment by eplanet** [comment]
I think #7 fixed that :-).
